package by.maxsel.xmlstuff;

import by.maxsel.xmlstuff.autogenerated.*;

import java.io.File;
import javax.xml.XMLConstants;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import org.xml.sax.SAXException;

public class UnMarshalWithXSD {
    public static Gems unmarshal() {
        JAXBContext jc = null;
        try {
            jc = JAXBContext.newInstance("by.maxsel.xmlstuff.autogenerated");
            Unmarshaller um = jc.createUnmarshaller();
            String schemaName = "data/gems.xsd";
            SchemaFactory factory =
                    SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            File schemaLocation = new File(schemaName);

            Schema schema = factory.newSchema(schemaLocation);
            um.setSchema(schema);
            Gems st =
                    (Gems) um.unmarshal(new File("data/gems.xml"));

            System.out.println(st);
            return st;
        } catch (JAXBException | SAXException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String[] args) {
        JAXBContext jc = null;
        try {
            jc = JAXBContext.newInstance("by.maxsel.xmlstuff.autogenerated");
            Unmarshaller um = jc.createUnmarshaller();
            String schemaName = "data/gems.xsd";
            SchemaFactory factory =
                    SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            File schemaLocation = new File(schemaName);

            // создание схемы и перадача ее демарашаллизатору
            Schema schema = factory.newSchema(schemaLocation);
            um.setSchema(schema);
            Gems st =
                    (Gems) um.unmarshal(new File("data/gems.xml"));

            //System.out.println(st);
        } catch (JAXBException e) {
            e.printStackTrace();
        } catch (SAXException e) {
            e.printStackTrace();
        }
    }
}